### ISSUE TITLE
Licensefile missing

### ISSUE THREAD

**Issue by fty4** [craigrodway/classroombookings#19]
Hello
in the description you tell your software is open source but there is no licence file in your repository.

Could you add one? That would be great!

Thank you for contributing to open source and sharing this :)

Best regards

**Comment by craigrodway** [comment]
Hi, you're right, that's a bit of an oversight! I'll get one added :)

**Comment by craigrodway** [comment]
Hi @fty4, I've now added the license (AGPLv3) file. Previous iterations of the website and development branches mentioned it, along with the key in `composer.json` - but now it's much clearer. Thanks for the nudge!
