### ISSUE TITLE
iCal for users/rooms

### ISSUE THREAD

**Issue by craigrodway** [craigrodway/classroombookings#2]
iCal for rooms and users' bookings. Might be useful for people wanting to 
have their bookings showing in their own Outlook/Email calendar.

/ical/room/ict1 - all entries in this room.
/ical/room/ict1/timetable - timetable bookings
/ical/room/ict1/single - single bookings

/ical/user/jsmith - all bookings for this user
/ical/user/jsmith/timetable - timetable bookings
/ical/user/jsmith/single - single bookings

**Comment by Kimosaj** [comment]
Is this now a possible feature? Because I can´t find any option to export the calendar.

**Comment by craigrodway** [comment]
Hi @Kimosaj, no, this feature hasn't been added yet.

**Comment by Kimosaj** [comment]
Oh man that´s bad because I want to integrate the bookings to a SmartHome System where my thermostats where controlled.
Is there an other option to get access to the made bookings? Like an API or direct connect to the database.

**Comment by craigrodway** [comment]
Sounds like an interesting project! There's no API yet either, but I presume you're running the self-hosted version - in which case, you are welcome to query the database directly to access your bookings.
