### ISSUE TITLE
v2.3.0-beta.1 - Problem

### ISSUE THREAD

**Issue by k9mjl** [craigrodway/classroombookings#21]
When clicking on the Settings or Authentication buttons it delivers a white screen with the message below.

404 Page Not Found
The page you requested was not found.

URL: 
http://roombooking.domainname.co.uk/index.php/settings/authentication/ldap
http://roombooking.domainname.co.uk/index.php/settings/general

**Comment by craigrodway** [comment]
Hi!

- Is this a new install or an upgrade?
- If it's an upgrade, did you completely replace the 'application' and 'assets' folders? (It's not enough to just copy over the new folders, you must move/delete the previous ones).
- Check if the file `application/controllers/settings/Authentication.php` file exists.

**Comment by k9mjl** [comment]
It was an upgrade, and no, I hadnt replaced the folders, I have just done that and its now opening those pages.

Thanks

**Comment by k9mjl** [comment]
LDAP settings completed but cant authenticate - LDAP bind error or bad username and/or password.

**Comment by craigrodway** [comment]
Please provide some more details about your setup.

- What values/settings are you using?
- Which version have you specified?
- Have you tried with and without TLS?

The Bind DN that will be used is:

`[attribute]=[username],[base_dn]`

So if your user attribute is `uid` and you test the credentials as `jsmith`, and your Base DN is `dc=example,dc=com`, then the full bind DN will be:

`uid=jsmith,dc=example,dc=com`

Can you authenticate via other means as that user using that format?

**Comment by k9mjl** [comment]
Fixed in Beta 2
