### ISSUE TITLE
Message

### ISSUE THREAD

**Issue by k9mjl** [craigrodway/classroombookings#22]
Is there any way of adding a message to the login page? The ability to add a short message would be great.

**Comment by KitGit65** [comment]
I was able to add some standard html in the login page php file. Just above the login area.  Perhaps that would work for you.

**Comment by craigrodway** [comment]
Started work on adding a section to the Settings page for this!

**Comment by KitGit65** [comment]
Thank you Craig! I have used this for Covid-19 related messages and room procedures.

**Comment by craigrodway** [comment]
This has been added in 2.4.0.
