### ISSUE TITLE
Ability to hide weekends

### ISSUE THREAD

**Issue by summmat** [craigrodway/classroombookings#24]
As a school we are only open Monday to Friday - could we have the ability to hide Saturday/Sunday?

Teachers sometimes get confused when they click 'next day' and get told there are 'no periods configured' etc.

**Comment by craigrodway** [comment]
Thanks! I'll take this on board for consideration.

**Comment by craigrodway** [comment]
This is now present from 2.4.0.

**Comment by usmantechson** [comment]
Can we schedule bookings on Saturday and Sunday too? @craigrodway

**Comment by craigrodway** [comment]
> Can we schedule bookings on Saturday and Sunday too? @craigrodway

Yes, that has always been possible and still is; this issue is not related.
