### ISSUE TITLE
Lesson Fee Collection

### ISSUE THREAD

**Issue by AnonJervis** [craigrodway/classroombookings#25]
Hi, great piece of software! Have you thought of adding fee collection per session or per classroom use? That would be a great addition to this!

**Comment by craigrodway** [comment]
Hi! Collecting money for bookings isn't something I'm considering at the moment. If there becomes sufficient demand for it in the future I may look at it again.

Thanks!

**Comment by AnonJervis** [comment]
Ok thank you for the reply!
