### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by hmt** [craigrodway/classroombookings#28]
Great service!
It's very simple and easy to use but would it be possible to add translations? At least for the users?
Thank you

**Comment by craigrodway** [comment]
Hi, thanks for your comment!

Supporting translations is a planned feature, but is a big undertaking: nearly all existing words and phrases are spread across many different files. Extracting these and enabling translations will take some time.

It's definitely not off the table, I just have some other improvements to make before this can be done.

Craig.
