### ISSUE TITLE
Week cycle bug

### ISSUE THREAD

**Issue by skymarcos96** [craigrodway/classroombookings#33]
Hi, my name is Marcos and I would like to report a bug in classroombookings. In Week cycle, when you edit a week and uncheck every week, the system does not save, due to an if in line 149 of the Controllers, so that if the selection returns empty (false), it does not enter the condition and does not update .

```
if ($this->input->post('dates')) {
          $this->weeks_model->UpdateMondays($week_id, $this->input->post('dates'));
}
```

I hope you can understand, I'm still improving my English.

And a suggestion that I applied to the project is the possibility of updating all holidays for the current year.

**Comment by craigrodway** [comment]
Hi Marcos! Thanks for reporting that bug, it does seem valid.

I'm not going to work on a fix for this, as the academic year, week cycle and bookings is currently going through a big re-write, and this bug no longer exists in that updated code.

As a workaround for now, I would recommend picking at least one date, or deleting the week and creating a new one.
