### ISSUE TITLE
Server Error 500

### ISSUE THREAD

**Issue by SRB-Online** [craigrodway/classroombookings#37]
I've installed classroombooking (version 2.5) on an Windows/XAMPP-Environment.
Everytime when configured a room the booking and profile page run in a server error 500.
Do you know the issue?

**Comment by craigrodway** [comment]
Hi

No support is provided for the open source edition, particularly not for a version that isn't officially released yet.

Please check the documentation for [troubleshooting steps](https://docs.classroombookings.com/version/2.5/maintenance/troubleshooting.html#logging) you can follow to help identify and fix the problem.
