### ISSUE TITLE
Develop version 2.6 - Cannot make multiple recurring bookings

### ISSUE THREAD

**Issue by C4rl1tos** [craigrodway/classroombookings#38]
Hi and thanks for your useful project.
I'm testing develop release 2.6.2 and i noticed that i cannot make a recursive booking on multiple selections.
1) I pick "Enable multiple selection".
2) In the dialog i select "Recurring bookings every week ..."
3) No matter which option i select in the date range "Starting From..." <-> "Until" but clicking "next" doesn't have effect.

I attach screenshots.
Thanks.

![multiple](https://user-images.githubusercontent.com/102649437/160775227-42cc36f0-8ce5-4a0d-8f95-6e1f03453a48.png)
![single](https://user-images.githubusercontent.com/102649437/160775232-b7f938a4-8752-41fc-983d-a97db1946e6c.png)

**Comment by craigrodway** [comment]
Hi

There is no support provided for the open source version (and especially not for versions that also aren't officially released).

This functionality is working fine on the demo system and on the platform for hosted customers. Please follow the troubleshooting guide in the documentation, check your server log files, or use the browser's Developer Tools to help you identify the problem.

**Comment by C4rl1tos** [comment]
Ok,
 thank you!
Have a good day!
