### ISSUE TITLE
feature Vr 2.6.2

### ISSUE THREAD

**Issue by phuonglt0805** [craigrodway/classroombookings#41]
Hey Craig,
First of all: thank you for making this great tool.  I have some new ideas for you.
1 - highlight all bookings current user .
![image](https://user-images.githubusercontent.com/89070030/173104521-ef160f24-6d89-4985-ae1b-b44bbac419ff.png)

2 - multiple selection cancel bookings .
![Untitled](https://user-images.githubusercontent.com/89070030/173106528-20cb2191-8e97-4ee5-a6e5-183d11765ac1.png)

Thanks you

**Comment by craigrodway** [comment]
Hi phuonglt0805, thanks for your suggestions! I'll keep those under consideration for future development.
