### ISSUE TITLE
Enable Multiple Selection doesn't seem to work

### ISSUE THREAD

**Issue by headofcomputing** [craigrodway/classroombookings#42]
Hi Craig

Thank you once again for creating such an incredibly useful system. Thank you for your hard work on this new version. Added features look great. 

I was testing a couple of things and it has come to my attention that "Enable Multiple Selection" when checked by a "Teacher", it says bookings were created but the cells are not blocked. 
Tried to book multiple slots. 
![image](https://user-images.githubusercontent.com/64566230/176704169-fb524117-ff62-450a-9dca-9fa7d3ef1f50.png)

It says three bookings were created but it doesn't block those slots. 
![image](https://user-images.githubusercontent.com/64566230/176704649-18d48821-c73e-4dca-9455-87f5f6732445.png)

It does show 3 bookings on the dashboard as well
![image](https://user-images.githubusercontent.com/64566230/176705674-883750c7-953c-4eb0-a25a-aa00d1496b5d.png)

Users
![image](https://user-images.githubusercontent.com/64566230/176705238-4498188d-f26f-4ad1-a1e2-a310f3f210d1.png)

Am I missing something here?

**Comment by headofcomputing** [comment]
Looks this is true for only the users that are not assigned to any department. However, if a user is assigned to a department, this issue is not seen. But, if the multiple selection is done as an Administrator for the user that is not assigned to any department, it works. 

Log record when attempted by a user unassigned to any department:
_ERROR - 2022-06-30 17:43:16 --> Query error: Cannot add or update a child row: a foreign key constraint fails (`booking`.`bookings`, CONSTRAINT `fk_bookings_department` FOREIGN KEY (`department_id`) REFERENCES `departments` (`department_id`) ON DELETE SET NULL ON UPDATE CASCADE) - Invalid query: INSERT INTO `bookings` (`date`, `session_id`, `period_id`, `room_id`, `department_id`, `user_id`, `notes`, `created_at`, `created_by`) VALUES ('2022-08-09', 1, 1, 2, 0, 2, 'hello', '2022-06-30 17:43:16', 2)_

Log record when an Administrator does it on the behalf of the same user:
ERROR - 2022-06-30 17:50:57 --> Severity: Warning --> Undefined property: app\components\bookings\agent\MultiAgent::$admin C:\xampp\htdocs\booking\application\components\bookings\agent\BaseAgent.php 169

Does this mean every user must be assigned to a department?

**Comment by craigrodway** [comment]
Hi headofcomputing, thanks for the bug report and log submission - the detail has been very helpful in identifying the problem. 🙌

This bug does mean that users need to have a Department set, but this isn't the intended behaviour. (This is a legacy issue due to users having a `0` value for their Department ID instead of NULL when they don't have one, but the bookings tables enforce the Department constraint - and there won't be any Department with an ID of `0`, hence the errors.)

I'll work on a fix and publish another release as soon as possible.

**Comment by craigrodway** [comment]
Hi again, thanks for your patience with this.

I've just released 2.6.4 which addresses this problem.
