### ISSUE TITLE
Blank page on creating booking

### ISSUE THREAD

**Issue by joe90bass** [craigrodway/classroombookings#43]
Thanks for such a great system! After updating to 2.6.3 we're having a minor issue when creating bookings, after entering the details in the create booking dialog box and clicking create booking the screen clears and we're just left with the background. Manually refreshing the webpage brings the screen back with the booking completed. This occurs for other users and whether it's a single booking or recurring.
It's not a gamestopper though :-) 

Creating the booking:
![create](https://user-images.githubusercontent.com/108941025/178009575-5564b2bc-5ec9-4c12-9ff8-213828c502ec.jpg)

Blank screen
![create2](https://user-images.githubusercontent.com/108941025/178009583-c5fb2773-0fbd-48ee-befc-d24e6be9f54b.jpg)

Thanks

**Comment by craigrodway** [comment]
Hi @joe90bass, thanks for reporting the issue.

I haven't come across this specific problem before, and can't quite work out what's going on there.

- Do you have any errors in your browser developer tools console? If you can, use the 'Network' tab to monitor for a request when you click the final Submit button to make the booking; then click the request to see if there are any clues/issues.
- Do you get any entries in the log file on the server? (a file in /local/logs with today's date)
- Does it happen on the demo? (linked from the website)

**Comment by craigrodway** [comment]
Hi Chris, thanks for the follow-up. A large portion of the system has been re-written in version 2.6 which is likely the cause of this.

I'm still having difficulty replicating this exact problem though. Is your instance publicly-accessible over the internet? I'll be happy to have a look if you can share test account credentials (privately, of course).

Craig.

**Comment by joe90bass** [comment]
Apologies for the delay. Unfortunately it's not publicly accessible. I'm going to go through the install instructions again, in case I've missed something obvious (though it shouldn't have worked prior to the upgrade if I have!)

**Comment by joe90bass** [comment]
Is it okay go through the install again? It won't reset any bookings?

**Comment by craigrodway** [comment]
Hi Chris, the install process will only work on empty databases.

I'd recommend trying a fresh install in a completely separate/blank database to see if the problem is still there.

**Comment by craigrodway** [comment]
Thanks for checking.

Can you get some logs from the Developer Tools so I can try to see what's happening?

The guidance is different depending on browser but this should help - https://toolbox.googleapps.com/apps/har_analyzer/.

It'll be most helpful to open the Developer Tools only once you're at the modal dialog (your first screenshot in this issue) that asks for the booking details.

**Comment by craigrodway** [comment]
Hi Chris

It looks like the PHP framework implements a fix/workaround for sending page redirects when running under IIS, which seemed like more of a problem with older versions of IIS dating back to v7. Having tested it on IIS 10, the standard HTTP redirect headers/codes work fine.

Until I release a new version of classroombookings, you can fix this in your own installations by putting a custom "MY_url_helper.php" file in application/helpers containing a function that overrides the default framework behaviour. [url=https://gist.github.com/craigrodway/3e6a354e4d13eebd47e3804ea5d96285]View the code here[/url] - click the 'Raw' button, right-click on the page, then save-as. Just make sure the file extension is .php, not .php.txt.

Please let me know if that fixes it for you.

**Comment by joe90bass** [comment]
Hi Craig,
Apologies for not getting back to you with the previous request for logs. I’ve tested the php fix you mention and it looks to have resolved the issue.

Many Thanks for your assistance with this,

Chris

From: Craig A Rodway ***@***.***>
Date: Friday, 5 August 2022 at 12:43
To: craigrodway/classroombookings ***@***.***>
Cc: Chris Cronin ***@***.***>, Mention ***@***.***>
Subject: Re: [craigrodway/classroombookings] Blank page on creating booking (Issue #43)

Hi Chris

It looks like the PHP framework implements a fix/workaround for sending page redirects when running under IIS, which seemed like more of a problem with older versions of IIS dating back to v7. Having tested it on IIS 10, the standard HTTP redirect headers/codes work fine.

Until I release a new version of classroombookings, you can fix this in your own installations by putting a custom "MY_url_helper.php" file in application/helpers containing a function that overrides the default framework behaviour. [url=https://gist.github.com/craigrodway/3e6a354e4d13eebd47e3804ea5d96285]View the code here[/url] - click the 'Raw' button, right-click on the page, then save-as. Just make sure the file extension is .php, not .php.txt.

Please let me know if that fixes it for you.
