### ISSUE TITLE
External requests not working

### ISSUE THREAD

**Issue by fatcatt013** [craigrodway/classroombookings#45]
![image](https://user-images.githubusercontent.com/54073116/181563048-fca0c538-9bba-4747-a5d9-ff3c8440e3f6.png)
I am using Hubot and its post request doesn't work because it for some reason doesn't send the data correctly (i think).

My another problem though is that when I do that post request on index.php/login/submit which is basically a login form action it doesn't open a session on the server side when I do it with curl. I copied the request from dev tools which is used and it works only if I already have an open session in the browser.

![image](https://user-images.githubusercontent.com/54073116/181565233-dc1160be-e613-4408-a46e-83ae98fa22a8.png)

if I have an open session on the server already, it redirects me correctly to the logged in window, otherwise it just redirects me back to the login page.. (renders the login view as content)

**Comment by craigrodway** [comment]
Hi

Unfortunately I can't offer any proper guidance on this unsupported use case.

The only thing I can point you towards is the use of cookies, which are used to maintain the logged-in session. The ID is refreshed frequently during a session to maintain security. The cookie you are sent from the server should also be sent in any subsequent requests, as it identifies the user & client on the server.

**Comment by fatcatt013** [comment]
![image](https://user-images.githubusercontent.com/54073116/181715381-58b8d395-e457-4446-8bfc-7ba5f9fc37c8.png)

Is it this cookie?

**Comment by craigrodway** [comment]
Yes, that's the one.

**Comment by fatcatt013** [comment]
Yeah I see, also what is the mechanism behind the refreshing? it has expire date of like 20 seconds or something but when it reaches that time, it is still up (the value is still the same). I need to know that because Hubot will probably need to automatically renew it somehow. 

anyways, how does the refreshing work? as I said, the cookie doesnt expire after window refresh and the expiry date is in the psat

**Comment by craigrodway** [comment]
You will need to look into CodeIgniter 3's documentation for that.

I must stress that I cannot provide free support for this special use case that classroombookings wasn't designed for.

Craig.

**Comment by fatcatt013** [comment]
Alright, thanks for the suggestion though.
