### ISSUE TITLE
Strange booking request

### ISSUE THREAD

**Issue by fatcatt013** [craigrodway/classroombookings#46]
![image](https://user-images.githubusercontent.com/54073116/183614491-4b046842-b063-4907-a7ef-0728d8f7df63.png)

This is the POST request which is supposed to make a booking with admin user for another user, what I find strange about it is that in the Form Data there are multiple variables with same name (and sometimes even value).

Is this intentional and crucial for the app to work or is it safe to clean it up? I am working with a Node.js based application and I am triggering the form actions with fetch requests. Is there a way how do you work with the order all the things are set up or not?

I mean I get the reason why there are 2 user_id variables.. one for the person who booked and the other for the person who is being booked. But what about for example the date variable? There are 3 date varibales, 2 are exactly the same and the third is practically the same but in a different format.

**Comment by craigrodway** [comment]
Hi! Only one occurrence is actually required.

On the bookings form, there are some hidden fields which hold some initial and default values. Then, the visible fields (depending on booking and user type) which allow changing or overriding the value. When making bookings in normal circumstances, the last value from the visible fields will take precedence of the values in hidden fields.

![image](https://user-images.githubusercontent.com/83069/184329162-136a8296-0279-46d6-a7b0-bab302623be3.png)

If you are making standalone POST requests, you only need to include the field + values once.
