### ISSUE TITLE
Bulk Bookings

### ISSUE THREAD

**Issue by k9mjl** [craigrodway/classroombookings#47]
After running through the process of making a recurring booking, after hitting the 'create bookings' button,  I have to refresh the blank page in order to return to the booking calendar, is this being seen on other installs?

**Comment by craigrodway** [comment]
Hi, if you're running under IIS, this is a known issue but there is a fix. Please have a look at [my reply here in another issue ](https://github.com/craigrodway/classroombookings/issues/43#issuecomment-1206354044) for details on how to update your install to work around it.

**Comment by k9mjl** [comment]
Perfect. Problem fixed.
