### ISSUE TITLE
Feature request: All rooms the next 5 days overview

### ISSUE THREAD

**Issue by superdanyo** [craigrodway/classroombookings#56]
Hello Craig,

is it possible to add an overview for "All rooms the next 5 days" to see all bookings of the coming days/week?

It could be activated like the "One day at a time" and the "One room at a time" setting. Maybe a third option here.

In our case the available overview for 1 room in a weekly overview is not enough.

Thanks a lot
Daniel

**Comment by craigrodway** [comment]
Thanks for your suggestion Daniel! A list view for bookings is planned for future development which should help your situation.
