### ISSUE TITLE
User created booking unable to cancel their own booking

### ISSUE THREAD

**Issue by bamtan** [craigrodway/classroombookings#68]
Running self-hosted version 2.8.6.

Users who create a booking are unable to cancel their own booking. Only the Edit option appears. 

This is happening for both LDAP and local users. 

The admin account can cancel the booking.

https://www.classroombookings.com/docs/self-hosted/bookings/view-edit-and-cancel/

**Comment by craigrodway** [comment]
Is the booking the user wishes to cancel in the past?
